# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/configuration/#theme-parameters

colorScheme = "sapphire"
# darkMode = "auto"
# darkToggle = false
# logo = "img/logo.jpg"
description = "Santiago Villa Neighborhood Association (rocks)"
# mainSections = ["section1", "section2"]
# robots = ""
enableSearch = "true"

[homepage]
  layout = "custom" # valid options: page, profile, custom
  showRecent = false

[article]
  showDate = false
  dateFormat = "2 January 2006"
  showAuthor = false
  showBreadcrumbs = false
  showDraftLabel = true
  showEdit = false
  # editURL = "https://github.com/username/repo/"
  editAppendPath = true
  showHeadingAnchors = true
  showPagination = true
  showReadingTime = false
  showWordCount = false
  showTableOfContents = true
  # sharingLinks = ["facebook", "twitter", "pinterest", "reddit", "linkedin", "email"]

[list]
  showBreadcrumbs = true
  showSummary = true
  groupByYear = false
  showTableOfContents = true

[taxonomy]
  showTermCount = true

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""

[header]
  logo = "img/Logo_dark.png"
  logoDark = "img/Logo.png"
  showTitle = false
  layout = "hybrid"

[footer]
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true
