baseURL = 'https://drjkl.github.io/SVNA/'
languageCode = 'en-us'
title = 'Santiago Villa Neighborhood Association'
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

[params]
    custom_css = ["index.scss"]

[markup.goldmark.parser.attribute]
    block = true
